/*
 * This file is generated by jOOQ.
 */
package data.jooq;


import data.jooq.tables.Group;
import data.jooq.tables.GuestUser;
import data.jooq.tables.Participant;
import data.jooq.tables.RegisteredUser;
import data.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.group</code>.
     */
    public final Group GROUP = Group.GROUP;

    /**
     * The table <code>public.guest_user</code>.
     */
    public final GuestUser GUEST_USER = GuestUser.GUEST_USER;

    /**
     * The table <code>public.participant</code>.
     */
    public final Participant PARTICIPANT = Participant.PARTICIPANT;

    /**
     * The table <code>public.registered_user</code>.
     */
    public final RegisteredUser REGISTERED_USER = RegisteredUser.REGISTERED_USER;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Group.GROUP,
            GuestUser.GUEST_USER,
            Participant.PARTICIPANT,
            RegisteredUser.REGISTERED_USER,
            User.USER
        );
    }
}
