/*
 * This file is generated by jOOQ.
 */
package data.jooq;

import data.jooq.tables.AppGroup;
import data.jooq.tables.AppParticipant;
import data.jooq.tables.AppUser;
import data.jooq.tables.Guest;
import data.jooq.tables.RegisteredUser;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Public extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>public</code> */
  public static final Public PUBLIC = new Public();

  /** The table <code>public.app_group</code>. */
  public final AppGroup APP_GROUP = AppGroup.APP_GROUP;

  /** The table <code>public.app_participant</code>. */
  public final AppParticipant APP_PARTICIPANT = AppParticipant.APP_PARTICIPANT;

  /** The table <code>public.app_user</code>. */
  public final AppUser APP_USER = AppUser.APP_USER;

  /** The table <code>public.guest</code>. */
  public final Guest GUEST = Guest.GUEST;

  /** The table <code>public.registered_user</code>. */
  public final RegisteredUser REGISTERED_USER = RegisteredUser.REGISTERED_USER;

  /** No further instances allowed */
  private Public() {
    super("public", null);
  }

  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(
        AppGroup.APP_GROUP,
        AppParticipant.APP_PARTICIPANT,
        AppUser.APP_USER,
        Guest.GUEST,
        RegisteredUser.REGISTERED_USER);
  }
}
