/*
 * This file is generated by jOOQ.
 */
package data.jooq.tables.records;

import data.jooq.tables.AppGroup;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class AppGroupRecord extends UpdatableRecordImpl<AppGroupRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.app_group.uuid</code>. */
  public AppGroupRecord setUuid(UUID value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>public.app_group.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.app_group.name</code>. */
  public AppGroupRecord setName(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>public.app_group.name</code>. */
  public String getName() {
    return (String) get(1);
  }

  /** Setter for <code>public.app_group.created</code>. */
  public AppGroupRecord setCreated(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>public.app_group.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>public.app_group.last_modified</code>. */
  public AppGroupRecord setLastModified(LocalDateTime value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>public.app_group.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(3);
  }

  /** Setter for <code>public.app_group.invite</code>. */
  public AppGroupRecord setInvite(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>public.app_group.invite</code>. */
  public String getInvite() {
    return (String) get(4);
  }

  /** Setter for <code>public.app_group.status</code>. */
  public AppGroupRecord setStatus(Long value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>public.app_group.status</code>. */
  public Long getStatus() {
    return (Long) get(5);
  }

  /** Setter for <code>public.app_group.admin_uuid</code>. */
  public AppGroupRecord setAdminUuid(UUID value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>public.app_group.admin_uuid</code>. */
  public UUID getAdminUuid() {
    return (UUID) get(6);
  }

  /** Setter for <code>public.app_group.budget</code>. */
  public AppGroupRecord setBudget(Long value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>public.app_group.budget</code>. */
  public Long getBudget() {
    return (Long) get(7);
  }

  /** Setter for <code>public.app_group.description</code>. */
  public AppGroupRecord setDescription(String value) {
    set(8, value);
    return this;
  }

  /** Getter for <code>public.app_group.description</code>. */
  public String getDescription() {
    return (String) get(8);
  }

  /** Setter for <code>public.app_group.selection_date</code>. */
  public AppGroupRecord setSelectionDate(LocalDate value) {
    set(9, value);
    return this;
  }

  /** Getter for <code>public.app_group.selection_date</code>. */
  public LocalDate getSelectionDate() {
    return (LocalDate) get(9);
  }

  /** Setter for <code>public.app_group.reminder</code>. */
  public AppGroupRecord setReminder(Boolean value) {
    set(10, value);
    return this;
  }

  /** Getter for <code>public.app_group.reminder</code>. */
  public Boolean getReminder() {
    return (Boolean) get(10);
  }

  /** Setter for <code>public.app_group.unlikely_count</code>. */
  public AppGroupRecord setUnlikelyCount(Long value) {
    set(11, value);
    return this;
  }

  /** Getter for <code>public.app_group.unlikely_count</code>. */
  public Long getUnlikelyCount() {
    return (Long) get(11);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached AppGroupRecord */
  public AppGroupRecord() {
    super(AppGroup.APP_GROUP);
  }

  /** Create a detached, initialised AppGroupRecord */
  public AppGroupRecord(
      UUID uuid,
      String name,
      LocalDateTime created,
      LocalDateTime lastModified,
      String invite,
      Long status,
      UUID adminUuid,
      Long budget,
      String description,
      LocalDate selectionDate,
      Boolean reminder,
      Long unlikelyCount) {
    super(AppGroup.APP_GROUP);

    setUuid(uuid);
    setName(name);
    setCreated(created);
    setLastModified(lastModified);
    setInvite(invite);
    setStatus(status);
    setAdminUuid(adminUuid);
    setBudget(budget);
    setDescription(description);
    setSelectionDate(selectionDate);
    setReminder(reminder);
    setUnlikelyCount(unlikelyCount);
    resetChangedOnNotNull();
  }
}
