/*
 * This file is generated by jOOQ.
 */
package data.jooq.tables.records;

import data.jooq.tables.AppParticipant;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class AppParticipantRecord extends TableRecordImpl<AppParticipantRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.app_participant.group_uuid</code>. */
  public AppParticipantRecord setGroupUuid(UUID value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>public.app_participant.group_uuid</code>. */
  public UUID getGroupUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.app_participant.user_uuid</code>. */
  public AppParticipantRecord setUserUuid(UUID value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>public.app_participant.user_uuid</code>. */
  public UUID getUserUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.app_participant.created</code>. */
  public AppParticipantRecord setCreated(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>public.app_participant.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>public.app_participant.last_modified</code>. */
  public AppParticipantRecord setLastModified(LocalDateTime value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>public.app_participant.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(3);
  }

  /** Setter for <code>public.app_participant.excluded</code>. */
  public AppParticipantRecord setExcluded(UUID value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>public.app_participant.excluded</code>. */
  public UUID getExcluded() {
    return (UUID) get(4);
  }

  /** Setter for <code>public.app_participant.avoid</code>. */
  public AppParticipantRecord setAvoid(UUID value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>public.app_participant.avoid</code>. */
  public UUID getAvoid() {
    return (UUID) get(5);
  }

  /** Setter for <code>public.app_participant.interests</code>. */
  public AppParticipantRecord setInterests(String value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>public.app_participant.interests</code>. */
  public String getInterests() {
    return (String) get(6);
  }

  /** Setter for <code>public.app_participant.bengerl_uuid</code>. */
  public AppParticipantRecord setBengerlUuid(UUID value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>public.app_participant.bengerl_uuid</code>. */
  public UUID getBengerlUuid() {
    return (UUID) get(7);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached AppParticipantRecord */
  public AppParticipantRecord() {
    super(AppParticipant.APP_PARTICIPANT);
  }

  /** Create a detached, initialised AppParticipantRecord */
  public AppParticipantRecord(
      UUID groupUuid,
      UUID userUuid,
      LocalDateTime created,
      LocalDateTime lastModified,
      UUID excluded,
      UUID avoid,
      String interests,
      UUID bengerlUuid) {
    super(AppParticipant.APP_PARTICIPANT);

    setGroupUuid(groupUuid);
    setUserUuid(userUuid);
    setCreated(created);
    setLastModified(lastModified);
    setExcluded(excluded);
    setAvoid(avoid);
    setInterests(interests);
    setBengerlUuid(bengerlUuid);
    resetChangedOnNotNull();
  }
}
