/*
 * This file is generated by jOOQ.
 */
package data.jooq.tables.records;

import data.jooq.tables.AppUser;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.app_user.uuid</code>. */
  public AppUserRecord setUuid(UUID value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>public.app_user.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.app_user.created</code>. */
  public AppUserRecord setCreated(LocalDateTime value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>public.app_user.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.app_user.last_modified</code>. */
  public AppUserRecord setLastModified(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>public.app_user.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>public.app_user.email</code>. */
  public AppUserRecord setEmail(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>public.app_user.email</code>. */
  public String getEmail() {
    return (String) get(3);
  }

  /** Setter for <code>public.app_user.display_name</code>. */
  public AppUserRecord setDisplayName(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>public.app_user.display_name</code>. */
  public String getDisplayName() {
    return (String) get(4);
  }

  /** Setter for <code>public.app_user.icon</code>. */
  public AppUserRecord setIcon(String value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>public.app_user.icon</code>. */
  public String getIcon() {
    return (String) get(5);
  }

  /** Setter for <code>public.app_user.interests</code>. */
  public AppUserRecord setInterests(String value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>public.app_user.interests</code>. */
  public String getInterests() {
    return (String) get(6);
  }

  /** Setter for <code>public.app_user.is_guest</code>. */
  public AppUserRecord setIsGuest(Boolean value) {
    set(7, value);
    return this;
  }

  /** Getter for <code>public.app_user.is_guest</code>. */
  public Boolean getIsGuest() {
    return (Boolean) get(7);
  }

  /** Setter for <code>public.app_user.group_uuid</code>. */
  public AppUserRecord setGroupUuid(UUID value) {
    set(8, value);
    return this;
  }

  /** Getter for <code>public.app_user.group_uuid</code>. */
  public UUID getGroupUuid() {
    return (UUID) get(8);
  }

  /** Setter for <code>public.app_user.personal_invite</code>. */
  public AppUserRecord setPersonalInvite(String value) {
    set(9, value);
    return this;
  }

  /** Getter for <code>public.app_user.personal_invite</code>. */
  public String getPersonalInvite() {
    return (String) get(9);
  }

  /** Setter for <code>public.app_user.firebase_uid</code>. */
  public AppUserRecord setFirebaseUid(String value) {
    set(10, value);
    return this;
  }

  /** Getter for <code>public.app_user.firebase_uid</code>. */
  public String getFirebaseUid() {
    return (String) get(10);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached AppUserRecord */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /** Create a detached, initialised AppUserRecord */
  public AppUserRecord(
      UUID uuid,
      LocalDateTime created,
      LocalDateTime lastModified,
      String email,
      String displayName,
      String icon,
      String interests,
      Boolean isGuest,
      UUID groupUuid,
      String personalInvite,
      String firebaseUid) {
    super(AppUser.APP_USER);

    setUuid(uuid);
    setCreated(created);
    setLastModified(lastModified);
    setEmail(email);
    setDisplayName(displayName);
    setIcon(icon);
    setInterests(interests);
    setIsGuest(isGuest);
    setGroupUuid(groupUuid);
    setPersonalInvite(personalInvite);
    setFirebaseUid(firebaseUid);
    resetChangedOnNotNull();
  }
}
