/*
 * This file is generated by jOOQ.
 */
package data.jooq.tables.records;

import data.jooq.tables.Guest;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GuestRecord extends TableRecordImpl<GuestRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.guest.uuid</code>. */
  public GuestRecord setUuid(UUID value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>public.guest.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.guest.created</code>. */
  public GuestRecord setCreated(LocalDateTime value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>public.guest.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.guest.last_modified</code>. */
  public GuestRecord setLastModified(LocalDateTime value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>public.guest.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(2);
  }

  /** Setter for <code>public.guest.email</code>. */
  public GuestRecord setEmail(String value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>public.guest.email</code>. */
  public String getEmail() {
    return (String) get(3);
  }

  /** Setter for <code>public.guest.display_name</code>. */
  public GuestRecord setDisplayName(String value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>public.guest.display_name</code>. */
  public String getDisplayName() {
    return (String) get(4);
  }

  /** Setter for <code>public.guest.group_uuid</code>. */
  public GuestRecord setGroupUuid(UUID value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>public.guest.group_uuid</code>. */
  public UUID getGroupUuid() {
    return (UUID) get(5);
  }

  /** Setter for <code>public.guest.personal_invite</code>. */
  public GuestRecord setPersonalInvite(String value) {
    set(6, value);
    return this;
  }

  /** Getter for <code>public.guest.personal_invite</code>. */
  public String getPersonalInvite() {
    return (String) get(6);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached GuestRecord */
  public GuestRecord() {
    super(Guest.GUEST);
  }

  /** Create a detached, initialised GuestRecord */
  public GuestRecord(
      UUID uuid,
      LocalDateTime created,
      LocalDateTime lastModified,
      String email,
      String displayName,
      UUID groupUuid,
      String personalInvite) {
    super(Guest.GUEST);

    setUuid(uuid);
    setCreated(created);
    setLastModified(lastModified);
    setEmail(email);
    setDisplayName(displayName);
    setGroupUuid(groupUuid);
    setPersonalInvite(personalInvite);
    resetChangedOnNotNull();
  }
}
