/*
 * This file is generated by jOOQ.
 */
package data.jooq.tables.records;


import data.jooq.tables.RegisteredUser;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RegisteredUserRecord extends TableRecordImpl<RegisteredUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.registered_user.uuid</code>.
     */
    public RegisteredUserRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.registered_user.created</code>.
     */
    public RegisteredUserRecord setCreated(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.registered_user.last_modified</code>.
     */
    public RegisteredUserRecord setLastModified(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.last_modified</code>.
     */
    public LocalDateTime getLastModified() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.registered_user.email</code>.
     */
    public RegisteredUserRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.registered_user.display_name</code>.
     */
    public RegisteredUserRecord setDisplayName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.registered_user.icon</code>.
     */
    public RegisteredUserRecord setIcon(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.icon</code>.
     */
    public String getIcon() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.registered_user.interests</code>.
     */
    public RegisteredUserRecord setInterests(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.registered_user.interests</code>.
     */
    public String getInterests() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisteredUserRecord
     */
    public RegisteredUserRecord() {
        super(RegisteredUser.REGISTERED_USER);
    }

    /**
     * Create a detached, initialised RegisteredUserRecord
     */
    public RegisteredUserRecord(UUID uuid, LocalDateTime created, LocalDateTime lastModified, String email, String displayName, String icon, String interests) {
        super(RegisteredUser.REGISTERED_USER);

        setUuid(uuid);
        setCreated(created);
        setLastModified(lastModified);
        setEmail(email);
        setDisplayName(displayName);
        setIcon(icon);
        setInterests(interests);
        resetChangedOnNotNull();
    }
}
